[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciFiAnalysisTools = "b4afd74a-200e-56c5-86f2-542176f22525"

[compat]
Documenter = "1"
Literate = "2"
Plots = "1"
